### ISSUE TITLE
Can i use it to share image

### ISSUE THREAD

**Issue by ayodelesalimon** [OpenFlutter/flutter_share_me#1]
Can it be used to share images too.?

**Comment by lizhuoyuan** [comment]
Not working now

**Comment by junaiddurrani** [comment]
It gives me error (no implementation found for FlutterShareMe().shareToWhatsApp())

This error comes in all categories like facebook whats app Twitter and To System.

How i will solve this error ?

**Comment by lizhuoyuan** [comment]
0.4.0 Support sharing pictures to whatsapp
