### ISSUE TITLE
The Gradle failure 

### ISSUE THREAD

**Issue by lesiaki** [OpenFlutter/flutter_share_me#10]
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.

**Comment by lizhuoyuan** [comment]
Already supported androidx

**Comment by GianlucaCesari** [comment]
/hosted/pub.dartlang.org/flutter_share_me-0.4.0/android/src/main/java/zhuoyuan/li/fluttershareme/util/FileUtil.java:12: error: package androidx.core.content does not exist
import androidx.core.content.FileProvider;
                            ^

This is the error it fires on version ^0.4.0

**Comment by lizhuoyuan** [comment]
Is there any introduction to androidx?

**Comment by VickySalunkhe** [comment]
The issue is still present I am using `flutter_share_me  0.5.0`

**Comment by VickySalunkhe** [comment]
> Is there any introduction to androidx?

you can find the documentation related to androidX here.
 https://goo.gl/CP92wY

**Comment by quantosapplications** [comment]
Hello, is this has been resolved?
I have this problem too with 0.6.0

**Comment by Todd-Tomorrow** [comment]
I had this same problem, also previously had upgraded to android x 
https://stackoverflow.com/a/57548381/8370475 worked for me

This problem was resolved by adding the colours in the android/app/src/res/values/colors.xml

<color name="com_facebook_button_background_color_focused_disabled">#3C5A99</color>
    <color name="com_facebook_button_background_color_focused">#3C5A99</color>
    <color name="com_facebook_button_border_color_focused">#3C5A99</color>
