### ISSUE TITLE
Specs satisfying the `FBSDKCoreKit (= 15.0.0), FBSDKCoreKit (~> 14.0.0)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by vincentwen-oo** [OpenFlutter/flutter_share_me#105]
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    FBSDKCoreKit (= 15.0.0)

    flutter_share_me (from `.symlinks/plugins/flutter_share_me/ios`) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 14.0.0)

Specs satisfying the `FBSDKCoreKit (= 15.0.0), FBSDKCoreKit (~> 14.0.0)` dependency were found, but they required a higher minimum deployment target.

platform :ios, '12.0'
flutter_share_me: ^1.4.0

**Comment by vincentwen-oo** [comment]
https://cocoapods.org/pods/FBSDKCoreKit

**Comment by lironzemingo** [comment]
@vincentwen-oo how did you solve this?
