### ISSUE TITLE
flutter_share_me 和 flutter_webview_plugin  冲突了

### ISSUE THREAD

**Issue by lessthanno** [OpenFlutter/flutter_share_me#12]
error:
Attribute provider#androidx.core.content.FileProvider@authorities value=(com.freeupapp.freeup.provider) from [:flutter_share_me] AndroidManifest.xml:16:13-60
	is also present at [:flutter_webview_plugin] AndroidManifest.xml:11:13-64 value=(com.freeupapp.freeup.fileprovider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:14:9-22:20 to override.
/Users/feature_ZH/Documents/FreeUpApp/freeup_app/android/app/src/debug/AndroidManifest.xml:18:17-72 Error:
	Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/file_paths) from [:image_picker] AndroidManifest.xml:18:17-72
	is also present at [:flutter_webview_plugin] AndroidManifest.xml:17:17-50 value=(@xml/filepaths).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by lizhuoyuan** [comment]
不出意外是fileprovider的问题
你试着将两个包的fileprovider的目录(好像是叫目录) 就com.xx.xx之类的一个东西改成一样的

**Comment by lessthanno** [comment]
给你发邮件了

**Comment by lizhuoyuan** [comment]
邮件没看到你说别的呀?  看起来跟github上的内容没有区别

**Comment by VickySalunkhe** [comment]
@lizhuoyuan
I am also facing the same issue


I am using flutter_webview_plugin in my app
and when I tried to build the app this was the error
and it had something related to flutter_share_me package .
D:\vicky\Work\WritCo\writco\android\app\src\debug\AndroidManifest.xml:17:17-50 Error:
Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/filepaths) from [:flutter_webview_plugin] AndroidManifest.xml:17:17-50
is also present at [:flutter_share_me] AndroidManifest.xml:21:17-51 value=(@xml/file_paths).
Suggestion: add 'tools:replace="android:resource"' to element at AndroidManifest.xml to override.
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:processDebugManifest'.
Manifest merger failed : Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/filepaths) from [:flutter_webview_plugin] AndroidManifest.xml:17:17-50
is also present at [:flutter_share_me] AndroidManifest.xml:21:17-51 value=(@xml/file_paths).
Suggestion: add 'tools:replace="android:resource"' to element at AndroidManifest.xml to override.
I was not able to figure it out so can anyone suggest anything ?

**Comment by lizhuoyuan** [comment]
try  flutter_webview_plugin 0.2.1  +2

**Comment by VickySalunkhe** [comment]
hi @lizhuoyuan that version is too old,  can you please fix that issue and publish a new package thankyou for creating a great package.

**Comment by lizhuoyuan** [comment]
> hi @lizhuoyuan that version is too old, can you please fix that issue and publish a new package thankyou for creating a great package.

I will try.

**Comment by lizhuoyuan** [comment]
0.6.0
