### ISSUE TITLE
Warning when tried to built the app

### ISSUE THREAD

**Issue by VickySalunkhe** [OpenFlutter/flutter_share_me#13]
I received an warning when tried to build the app.

> Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_share_me-0.5.0\android\src\main\java\zhuoyuan\li\fluttershareme\util\FileUtil.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by lizhuoyuan** [comment]
Just an outdated api, don't care too much

**Comment by VickySalunkhe** [comment]
was just letting you know about the warning.
