### ISSUE TITLE
ApplicationID Facebook

### ISSUE THREAD

**Issue by ederluca** [OpenFlutter/flutter_share_me#19]
In the documentation says I need to add the following line in AndroidManifest.xml:

             android: name = "com.facebook.sdk.ApplicationId"
             android: value = "@ string / facebook_app_id" />            

I believe I am not able to report this correctly because when I inform I can not compile nor trigger the debug mode of application Applicationid of my application is com.home how to proceed to inform correctly?

**Comment by lizhuoyuan** [comment]
I just submited 0.8.0  ,  I don't know if it is your idea.
