### ISSUE TITLE
How add this pub in web project?

### ISSUE THREAD

**Issue by dev01mrrocco** [OpenFlutter/flutter_share_me#21]
How add this pub in web project? I don't know how to setting, for example, add facebook config. I would like that you show tutorial how add this configuration. Thanks!

**Comment by lizhuoyuan** [comment]
web? Do you mean to open your browser and jump to the address of facebook?

**Comment by dev01mrrocco** [comment]
That's right. I saw that this pub is compatible with the web, but there is no tutorial and could not open or share something on social networks, such as on facebook. How could I do such an action? Thanks!

**Comment by lizhuoyuan** [comment]
Sorry . 
This plugin uses the SDK provided by Facebook and Android to open other applications to achieve the sharing function, and may not be applicable to you

**Comment by Drolegc** [comment]
> Sorry .
> This plugin uses the SDK provided by Facebook and Android to open other applications to achieve the sharing function, and may not be applicable to you

Please, remove compatibility platforms on pub.dev, because this package appears to work only on Android
