### ISSUE TITLE
.aab fails to upload to Google Play

### ISSUE THREAD

**Issue by kenthor** [OpenFlutter/flutter_share_me#32]
I'm using version 0.9.1 of this plug-in.

Everything works fine when I build an apk and test this on both the emulator and on a real device.
I'm also able to build a final release version as an .aab file without problems, but this .aab file is not accepted when uploading it to Google Play (through Google Play Console). There is no error message to explain the reason for the upload failure.

It turns out that the .aab file is considered to be invalid because of an invalid resource contained in the Facebook Android SDK ver. 5.9.0 (which this plug-in uses).

I was able to create a valid .aab file using the solution found here:
https://stackoverflow.com/questions/58924089/error-when-trying-upload-aab-to-google-play-console-res-values-fb

Of course, the real fix is for this plug-in to use the updated version of the Facebook SDK.

**Comment by mateushoeckler** [comment]
Same problem, thanks!

**Comment by lizhuoyuan** [comment]
I will modify to the latest version as soon as possible
