### ISSUE TITLE
share to whatsapp not working

### ISSUE THREAD

**Issue by armandojimenez** [OpenFlutter/flutter_share_me#36]
getting this error on ios

VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, Object>' in type cast
#0      FlutterShareMe.shareToWhatsApp
package:flutter_share_me/flutter_share_me.dart:37
#1      _SharePageState._shareToWhatsapp.<anonymous closure>
package:believe/…/pages/share_page.dart:424
<asynchronous suspension>

**Comment by armandojimenez** [comment]
Anyone know how to fix this?

**Comment by lizhuoyuan** [comment]
`package:believe/…/pages/share_page.dart:424`
Maybe there is a problem with the type of data received here, try using var?

**Comment by armandojimenez** [comment]
Even if I pass nothing, so it uses the default empty value, it crash at the first line when trying to cast 
final Map<String, Object> arguments = Map<String, dynamic>() as Map<String, Object>;

**Comment by lizhuoyuan** [comment]
I’m not sure what type of result is returned. I suggest you print it first. It may be because the data types are inconsistent and cannot be forced.
