### ISSUE TITLE
Map<String, dynamic>() as Map<String, Object>; Runing error

### ISSUE THREAD

**Issue by sis-tangyuan** [OpenFlutter/flutter_share_me#38]
E/flutter (27281): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, Object>' in type cast
E/flutter (27281): #0      FlutterShareMe.shareToFacebook (package:flutter_share_me/flutter_share_me.dart:8:66)

**Comment by armandojimenez** [comment]
Same error I have in #36, still no solution
