### ISSUE TITLE
Share image to whatsapp

### ISSUE THREAD

**Issue by gkmuhannad** [OpenFlutter/flutter_share_me#44]
Hi
Share the image to whats app not working,
it just. take the message and ignore the image

**Comment by lizhuoyuan** [comment]
ios or android?
and version?

**Comment by gkmuhannad** [comment]
Android version 10
&
I didn't test on ios


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lizhuoyuan** [comment]
If the parameter of the picture is base64

**Comment by lizhuoyuan** [comment]
try new version plz

**Comment by gkmuhannad** [comment]
ok I will and let you know
thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gkmuhannad** [comment]
sorry for late response 
the same problem my friend
this is my code 

`  final directory = await getApplicationDocumentsDirectory();
      final imagePath = await File('${directory.path}/${gift.id}.png').create();
      final Uint8List pngBytes = capturedImage.buffer.asUint8List();
      await imagePath.writeAsBytes(pngBytes);
      String base64Image = base64Encode(pngBytes);
      print("base64Image $base64Image");
      var response = await FlutterShareMe()
          .shareToWhatsApp(msg: "*", imagePath: base64Image);
      print("response $response");`

**Comment by lizhuoyuan** [comment]
print("base64Image $base64Image");
please show this result.
And
I am modifying the project, you can rely on the address of github and share the pictures using the local path.

**Comment by gkmuhannad** [comment]
Hi
it is work now thanks without converting to base64 
just with file path

thanks for your support

**Comment by gkmuhannad** [comment]
I got these errors when I tried to run on an ios device:
* I am not using Facebook sharing 

 /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/Toast/Toast/UIView+Toast.m:398:118: warning: 'UIActivityIndicatorViewStyleWhiteLarge' is deprecated: first deprecated in iOS 13.0 [-Wdeprecated-declarations]
        UIActivityIndicatorView *activityIndicatorView = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhiteLarge];
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                          UIActivityIndicatorViewStyleLarge
    In module 'UIKit' imported from /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/Target Support Files/Toast/Toast-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIActivityIndicatorView.h:18:5: note: 'UIActivityIndicatorViewStyleWhiteLarge' has been explicitly marked deprecated here
        UIActivityIndicatorViewStyleWhiteLarge API_DEPRECATED_WITH_REPLACEMENT("UIActivityIndicatorViewStyleLarge", ios(2.0, 13.0), tvos(9.0, 13.0)) = 0,
        ^
    1 warning generated.
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/libPhoneNumber-iOS/libPhoneNumber/NBPhoneNumberUtil.m:3482:51: warning: 'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0 [-Wdeprecated-declarations]
      NSString *isoCode = [[self.telephonyNetworkInfo subscriberCellularProvider] isoCountryCode];
                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                      serviceSubscriberCellularProviders
    In module 'CoreTelephony' imported from /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/libPhoneNumber-iOS/libPhoneNumber/NBPhoneNumberUtil.m:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: property 'subscriberCellularProvider' is declared deprecated here
    @property(readonly, retain, nullable) CTCarrier *subscriberCellularProvider API_DEPRECATED_WITH_REPLACEMENT("serviceSubscriberCellularProviders", ios(4.0, 12.0)) API_UNAVAILABLE(macos);
                                                     ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/CoreTelephony.framework/Headers/CTTelephonyNetworkInfo.h:112:50: note: 'subscriberCellularProvider' has been explicitly marked deprecated here
    1 warning generated.
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog/FBSDKWebDialogView.m:69:84: warning: 'UIActivityIndicatorViewStyleWhiteLarge' is deprecated: first deprecated in iOS 13.0 [-Wdeprecated-declarations]
        _loadingView = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleWhiteLarge];
                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                       UIActivityIndicatorViewStyleLarge
    In module 'UIKit' imported from /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/Target Support Files/FBSDKCoreKit/FBSDKCoreKit-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIActivityIndicatorView.h:18:5: note: 'UIActivityIndicatorViewStyleWhiteLarge' has been explicitly marked deprecated here
        UIActivityIndicatorViewStyleWhiteLarge API_DEPRECATED_WITH_REPLACEMENT("UIActivityIndicatorViewStyleLarge", ios(2.0, 13.0), tvos(9.0, 13.0)) = 0,
        ^
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog/FBSDKWebDialogView.m:114:7: warning: 'UI_USER_INTERFACE_IDIOM' is deprecated: first deprecated in iOS 13.0 - Use -[UIDevice userInterfaceIdiom] directly. [-Wdeprecated-declarations]
      if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {
          ^
    In module 'UIKit' imported from /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/Target Support Files/FBSDKCoreKit/FBSDKCoreKit-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIDevice.h:97:36: note: 'UI_USER_INTERFACE_IDIOM' has been explicitly marked deprecated here
    static inline UIUserInterfaceIdiom UI_USER_INTERFACE_IDIOM() API_DEPRECATED("Use -[UIDevice userInterfaceIdiom] directly.", ios(2.0, 13.0), tvos(9.0, 11.0)) {
                                       ^
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog/FBSDKWebDialogView.m:170:57: error: unknown receiver 'FBSDKBasicUtility'; did you mean 'FBSDKTypeUtility'?
        NSMutableDictionary<NSString *, id> *parameters = [[FBSDKBasicUtility dictionaryWithQueryString:URL.query] mutableCopy];
                                                            ^~~~~~~~~~~~~~~~~
                                                            FBSDKTypeUtility
    In file included from /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog/FBSDKWebDialogView.m:30:
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Basics/Internal/FBSDKTypeUtility.h:22:12: note: 'FBSDKTypeUtility' declared here
    @interface FBSDKTypeUtility : NSObject
               ^
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog/FBSDKWebDialogView.m:170:75: error: no known class method for selector 'dictionaryWithQueryString:'
        NSMutableDictionary<NSString *, id> *parameters = [[FBSDKBasicUtility dictionaryWithQueryString:URL.query] mutableCopy];
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog/FBSDKWebDialogView.m:171:43: error: unknown receiver 'FBSDKBasicUtility'; did you mean 'FBSDKTypeUtility'?
        [parameters addEntriesFromDictionary:[FBSDKBasicUtility dictionaryWithQueryString:URL.fragment]];
                                              ^~~~~~~~~~~~~~~~~
                                              FBSDKTypeUtility
    In file included from /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog/FBSDKWebDialogView.m:30:
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Basics/Internal/FBSDKTypeUtility.h:22:12: note: 'FBSDKTypeUtility' declared here
    @interface FBSDKTypeUtility : NSObject
               ^
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog/FBSDKWebDialogView.m:171:61: error: no known class method for selector 'dictionaryWithQueryString:'
        [parameters addEntriesFromDictionary:[FBSDKBasicUtility dictionaryWithQueryString:URL.fragment]];
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/Internal/WebDialog/FBSDKWebDialogView.m:186:40: warning: 'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
        [[UIApplication sharedApplication] openURL:URL];
                                           ^~~~~~~
                                           openURL:options:completionHandler:
    In module 'UIKit' imported from /Users/henno/Desktop/SARAHAH/sarahah/ios/Pods/Target Support Files/FBSDKCoreKit/FBSDKCoreKit-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:123:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0)) NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    3 warnings and 4 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

**Comment by jigarfumakiya** [comment]
Can you please try below
Flutter clean
pod update

**Comment by gkmuhannad** [comment]
Thank you so much bro😍
it works

**Comment by jigarfumakiya** [comment]
perfect
Closing this issue.

**Comment by gkmuhannad** [comment]
it is happening again,
I did the flutter clean & pod update but still not working 
 
 Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_FBSDKShareLinkContent", referenced from:
          objc-class-ref in SwiftFlutterShareMePlugin.o
      "_OBJC_CLASS_$_FBSDKShareDialog", referenced from:
          objc-class-ref in SwiftFlutterShareMePlugin.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
