### ISSUE TITLE
Hardcoded Application ID

### ISSUE THREAD

**Issue by nodinosaur** [OpenFlutter/flutter_share_me#5]
## DO NOT USE THIS LIBRARY UNTIL THESE ISSUES ARE FIXED

There is a hard coded application ID.
[FlutterShareMePlugin.java Line 136](https://github.com/OpenFlutter/flutter_share_me/blob/master/android/src/main/java/zhuoyuan/li/fluttershareme/FlutterShareMePlugin.java#L136)

Please review [flutter_facebook_login](https://github.com/nodinosaur/flutter_facebook_login/blob/master/README.md)

On how you should be handling this.

**Comment by nodinosaur** [comment]
The Application ID has also been hard coded into the Android Manifest:
[AndroidManifest.xml Line 7](https://github.com/OpenFlutter/flutter_share_me/blob/master/android/src/main/AndroidManifest.xml#L7)


*DO NOT USE THIS LIBRARY UNTIL THESE ISSUES ARE FIXED*

**Comment by lizhuoyuan** [comment]
[AndroidManifest.xml Line 7]

**Comment by nodinosaur** [comment]
OK, that is part of it... and the rest please

Also, look into how to run Mac OS X in a VM so you can run Xcode and iOS simulator, incomplete libraries should not even be listed on https://pub.dartlang.org/packages

**Comment by lizhuoyuan** [comment]
thanks for your suggestion
