### ISSUE TITLE
Failed to share at WhatsApp. Getting message "sharing failed. please try again later"

### ISSUE THREAD

**Issue by ZoraizEjaz** [OpenFlutter/flutter_share_me#54]
Failed to share at WhatsApp. Getting message "sharing failed. please try again later" at Android OS.

**Comment by Nag112** [comment]
Same issue . Did you find any solution?

**Comment by Nag112** [comment]
make sure imagePath is not null

**Comment by Nag112** [comment]
I fixed the issue and created a pull request . Please try it .

**Comment by lizhuoyuan** [comment]
upgrade 1.1.4 please
