### ISSUE TITLE
facebook id 不要写死啊 & 而且都不支持 image分享啊  

### ISSUE THREAD

**Issue by lessthanno** [OpenFlutter/flutter_share_me#7]
我发现 facebook分享 id  是写死的

**Comment by lizhuoyuan** [comment]
facebook id 新版本可以自己编辑了
image 暂时不支持

**Comment by lessthanno** [comment]
求支持 image && 支持iOS ，特别是我这种时间不够，需求又多的，不然可以帮忙commit code！！！

**Comment by lizhuoyuan** [comment]
ios是真的无能为力了.
安卓上的图片因为之前的ContentProvider的问题所以放弃了.
有时间的话 , 考虑把图片这一块补上(android)

**Comment by lessthanno** [comment]
那我自己来补iOS把

**Comment by lizhuoyuan** [comment]
是哪里需要分享图片呢

**Comment by lessthanno** [comment]
whatapp 支持发送image

**Comment by lizhuoyuan** [comment]
已搞定, 0.4.0
