### ISSUE TITLE
Instagram video share

### ISSUE THREAD

**Issue by LeGoffMael** [OpenFlutter/flutter_share_me#72]
First, thank you for this plugin.

Looking at the [sharing feature description](https://developers.facebook.com/docs/instagram/sharing-to-feed?locale=en) document, video formats (mp4 & mkv) are also supported by Instagram.

Do you plan to add this option to `flutter_share_me` ?

This is a great feature that I look forward to seeing implemented.

Currently i am getting an error:

```bash
File format not supported Please check the file.
```

**Comment by LeGoffMael** [comment]
I made it working on my repository : https://github.com/LeGoffMael/flutter_share_me

I will make a PR later because i forked it from : https://github.com/jordanjanaq/flutter_share_me as i needed this change to compile on iOS

**Comment by lizhuoyuan** [comment]
Thanks for your contribution
