### ISSUE TITLE
Sharing to WhatsApp using their short Url

### ISSUE THREAD

**Issue by RakhimyanTim** [OpenFlutter/flutter_share_me#8]
Hi there!

Is it possible to share some content (image, text etc.) to WhatsApp using  https://wa.me/<phone number>

Thanks!

**Comment by lizhuoyuan** [comment]
Incorrect link! 
And , now support share image and text to WhatsApp.
What do you want?

**Comment by RakhimyanTim** [comment]
Incorrect because without phone number. 
It is WhatsApp's chip - allows send message without adding phone number to your contact list. 
Please find more [here](https://faq.whatsapp.com/en/android/26000030/?lang=kk).

**Comment by lizhuoyuan** [comment]
I think I understand what you mean. 
You want to share content with others through such a link. 
But I have not used this feature, and it should not be possible for the time being.

**Comment by RakhimyanTim** [comment]
Ok-ok. I see. Thank you for your quick answers!
